import { Itim } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const itim = Itim({
    subsets: ["latin"],
    weight: "400",
});

export default function RootLayout({ children }) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={itim.className}>{children}</body>
            </html>
        </ClerkProvider>
    );
}