import type { Metadata } from "next";
import { Itim } from "next/font/google";
import "./globals.css";
import {ClerkProvider} from "@clerk/nextjs";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const itim = Itim({
    subsets: ['latin'],
    weight: '400',
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider>
        <html lang="en">
          <body className={itim.className}>{children}</body>
        </html>
      </ClerkProvider>
  );
}
